### ISSUE TITLE
Change crypto scheme a little bit

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#11]
Right now, we're storing and passing the encryption keys in plain text. This sucks.

I (along with @landakram) propose a new scheme, which would eliminate some of these problems.
1. On extension installation, generate a public and private key. Store private key in local storage.
2. On first connection with Clef, send public key to server and store.
3. Whenever a new encryption key is generated, instantly encrypt it with the server-stored public key.
4. When Vault receives a encrypted encryption-key, it decrypts it with the private key it stores in its keychain and proceeds as normal with decrypting the password.

This scheme isn't really _that_ great because if an attacker has ahold of the encryption keys from our server _and_ the user's encrypted passwords, she almost certainly also has a hold of the private key. However, it does make me feel a little better because storing and passing things in plaintext never feels good.

Thoughts?

**Comment by josephwegner** [comment]
Correct me where I'm wrong...

The attack vector you're worried about is that an attacker has encrypted passwords (somehow stolen from the users computer) and the decryption keys (somehow stolen from Cydoemus..  MITM, db hack, etc.).  This would give the attacker everything he needs to decrypt the stolen passwords.

The solution you propose would be to encrypt the encryption keys (this is getting confusing...) so that an attacker couldn't use them to decrypt the stored passwords.  However, like you say, if the attacker gained access to the locally stored passwords, he would definitely have the private key as well.

I recognize - and agree with - your worry about storing the encryption keys in plain text.  However, I don't think this is the solution.  We would just be adding more friction to the same attack vector - not closing the hole.

Is it possible Clef could provide some user-specific salt from the info endpoint?  Just some randomly generated string that is HIGHLY RECOMMENDED NOT TO BE STORED..  If we use that as a cipher key, Cydoemus would only be able to decrypt the encryption keys (goodness, my tongue is tied) when the user is authenticated.

Actually, the above has sparked a good idea in general for Clef.  I will create a ticket on Clef's Github page, because it makes more sense there.

**Comment by jessepollak** [comment]
I'm going to close this for now.
