### ISSUE TITLE
Invalid credentials is broken on Hacker News

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#114]
1. Go to Hacker News home page
2. Type in bad credentials and submit
3. Taken back to hacker news home page and no invalid credentials page is displayed

**Comment by landakram** [comment]
Fixed for HN with https://github.com/waltzio/waltz/commit/eb640cab63da711eebebda4c07562f2555d4e718, but this is caused by the general issue that the wrong credentials form is displayed only if the login form is detected on the page. Since an improper login on HN results in a natural redirect to `/x`, which is not the login page, `/newslogin`, Waltz will force a redirect back to `/` and then will not display the wrong credentials form since `/` does not have a login form.
