### ISSUE TITLE
Reconfigure tutorial appearance options

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#126]
When should the tutorial tooltips appear for a site? Only if you click through?

Need to change this so it doesn't show up every time.

**Comment by jessepollak** [comment]
OK, I talked to @brennenbyrne and he likes the way the tutorial is configured right now.

Right now, the tutorial works this way:
- If you click from the tutorial page, it always shows
- If you haven't dismissed it by clicking the X in the top left:
  - On a new site, until you log in, it will show

@landakram @josephwegner thoughts?

**Comment by josephwegner** [comment]
I guess I don't mind terribly if the tutorial shows up every time you go to a site, as long as you have the option of permanently dismissing it.

However, I do still have issue with the waltz button being moved to the top right instead of the bottom right of the browser.  I think we're going to be annoying users with that placement, especially if the tutorial is opening all the time.

**Comment by jessepollak** [comment]
OK, I'm going to close this. Can you re open a new issue to discuss that?
