### ISSUE TITLE
Implement Bypass for 10 different sites with login and logout

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#13]
So far, we have:
- Facebook

IDEAS:
- Google (this one could be tricky)
- ~~Twitter~~
- Trello 
- Pivotal Tracker
- ~~Hacker News (should be very easy)~~
- Capital One

**Comment by josephwegner** [comment]
Should we focus on this list: https://getclef.com/websites ?

**Comment by jessepollak** [comment]
We definitely could.

**Comment by josephwegner** [comment]
Works for facebook, twitter, ycombinator...  Capital One is going to be tricky, but certainly possible.

I don't have Pivotal or Trello accounts.  Can you work on those?

**Comment by josephwegner** [comment]
Capital One login works, but log out doesn't.

The creds are stored on the login.capitalone.com domain, but the logged in domain is servicing.capitalone.com.  I think that's why logout doesn't work.  Any ideas, @jessepollak

**Comment by josephwegner** [comment]
Same issue with Google.  Login is stored on accounts.google.com, but logout is generally not there.

**Comment by jessepollak** [comment]
yeah, those are going to be trickier. I think we'll need to have edge cases. @brennenbyrne has discussed have basically a folder of site specific configs. This way, if someone wants to add a new site, they just drop in a google.js file and setup everything.

thoughts?

**Comment by josephwegner** [comment]
You mean a folder in the repo?  It would have to be - there's no folder on the system that the extension would be able to access.  At least, I don't think there is.

If we're going to do it in the repo, it's probably easiest to have one config file, and people can put PRs in on that config file.  Otherwise, every time they add a file they're also going to have to add it into the background scripts section of the manifest file.  That could get both messy and confusing.

Also, the rough part about doing that is we have to do an extension update every time a new site is added.

We _could_ possible store this in an API.  I think it's out of scope for Cydoemus - is there an already existing service that would be good for that?

**Comment by josephwegner** [comment]
Either way, though, there's a solution to the Capital One & Google problem.  I don't know exactly how the chrome cookie APIs work, but there's got to be a way to find all cookies for a root domain (ie: google.com, instead of accounts.google.com).  We can just log the user out of everything that way.

**Comment by jessepollak** [comment]
we could do some sort of build process that integrated them all in?

I'm not sure how I feel about the pull and update for new sites...that
seems wrong.

**Comment by josephwegner** [comment]
How would new sites get added without an extension update?  If the user installs through the chrome web store, they have no access to the extension files...

**Comment by jessepollak** [comment]
Yeah, I was agreeing with you on that :)

I'm not sure what to do.

**Comment by jessepollak** [comment]
Added Github

**Comment by jessepollak** [comment]
This is useless, closing.
