### ISSUE TITLE
Waltz Button Position

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#139]
The positioning of the Waltz widget was recently changed, moving it to the top right of the window.  It used to be in the bottom right.

I'm pretty heavily in favor of reverting back to the bottom right position.  Almost all sites have navigation in a header, and often times user/account/session settings are positioned to the right side of that header.  If the waltz button is coming up in the top right, we are covering up those navigation elements.

Now, the user can certainly just dismiss the waltz widget, but I don't see why we're intentionally creating friction.  Correct me if I'm missing something, but are there downsides to moving it back to the bottom right?

**Comment by jessepollak** [comment]
@brennenbyrne, comment please!

**Comment by iamb55** [comment]
This is something that Jesse and I have been talking about a bunch. Here's what happened that sparked the change: 

I was setting up Waltz on my computer (with a new release and testing out the tutorial). I got the plugin downloaded, and clicked that I wanted to set it up on Facebook first. I got to facebook, typed my username and password in the normal field, and logged in. Surprised that I had accidentally done the wrong thing, I restarted the tutorial and tried again. 10 times out of 10 I forgot that Waltz was there and accidentally typed my username and password in the normal fields. Even while I was intentionally testing Waltz out and trying to pay attention to it, kicking myself for forgetting the last 9 times in a row, I still missed it because my eye never goes to the bottom corner of my screen.

Now, I have a big monitor, and so it's probably more obvious when the window isn't as tall as mine, but the corner placement was hiding Waltz from me completely, so I've been pushing for a more prominent placement. I have a few thoughts - 1) we could fix it in that bottom corner, but make it a maximum of 600 pixels from the top, so that it doesn't get lost at the bottom of a big monitor like mine. 2) we can put it somewhere in the top where it is more prominent (bottom right corner covers important things too, facebook chat buttons, google hangout thumbnails, etc.) or 3) we can animate it much more prominently and make it much bigger. 

I'm definitely open to different options here, but that bottom corner made Waltz impossible for me to use.

**Comment by josephwegner** [comment]
Those are valid reasons.  I have a pretty large monitor and haven't had that problem, but missing it 10 out of 10 times is a pretty serious data point :)

I would be interested in doing option 1, though I'm wondering if the button might look like it's oddly floating at that 600px mark.

If it looks gross, I guess we can keep it in the top right and see what the user reaction is.  It's possible I'm only so bothered by it because I was used to it being in the bottom right.

**Comment by jessepollak** [comment]
Let's try it at 50% height for a little bit and see how we feel.
