### ISSUE TITLE
Generate unique ID for each set of credentials

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#218]
So, right now, we generate a unique encryption key for each site key (facebook, twitter, etc). These encryption keys are used to encrypt credentials on _all_ of your devices and they never change.

We're going to fix the never change thing with #185 (I've made a little progress on it), but is there a reason why we'd want these keys (even when rotated) to remain consistent across all devices?

I propose the following idea:
1. User inputs a new set of credentials and we are given `siteKey`, `username`, `password
2. waltzio/waltz generates a pseudo-random `credentialID,` which is uses as the identifier when requesting a new encryption key from waltzio/cy
3. waltzio/cy returns an `encryptionKey` that matches the `credentialID`
4. waltzio/waltz encryptions `password` with `encryptionKey`
5. waltzio/waltz stores under `siteKey` in the credentials object in local storage:

``` javascript
{
    id: credentialID,
    password: crypto.encrypt(password, encryptionKey),
    username: username
}
```
1. The next time user logs in with `siteKey`, we look up the credentials that match `siteKey`, pull out the appropriate `credentialID` and use that to get the correct `encryptionKey` from waltzio/cy

With this new scheme, we get a few benefits (I _think_ they are benefits at least):
- passwords are encrypted with different keys across different devices
- if you delete your credentials from a computer, then reencrypt, you get an automatic key rotation because the credentialID will change

thoughts @landakram @josephwegner

**Comment by jessepollak** [comment]
As you can see, I just added a PR, which would implement this functionality.

This definitely doesn't have to be merged, it was just a tiny change, so I figured I'd pull to see what you thought. Well, the unique ID part was a tiny change, but then I decided to also add in a refactor I'd started for the keyRotation stuff....even if we don't merge in the unique ID stuff, we can merge in that refactor if y'all like it.

**Comment by landakram** [comment]
I can't quite figure out the attack vector, but using a different key per credential per device just _seems_ like it's a good idea, so I'm in favor.

**Comment by landakram** [comment]
It might make it harder to sync credentials across devices in the future, but I think that will require a rather major re-jiggering anyway.

**Comment by jessepollak** [comment]
Yeah, that was my concern as well, but I think that it's going to require a different architecture, so I don't think we should let that limit this.

@josephwegner thoughts?

**Comment by josephwegner** [comment]
@landakram re-jiggering?  That's the first time I've heard that term :)

I think this is a good idea.  I've had it in the back of my head for awhile that we probably shouldn't be having Cy store the username..  Once we take the username out of Cy, anything stored in the Cy database becomes pretty much useless to an attacker (unless they get access to the user's device).

If we want these keys to be unique per device, it does make syncing pretty hard.  Right now, we could easily change to using Chrome's sync storage instead of local storage, and everything would automatically sync.  That would even work with these pseudo-random keys, but it would make them not unique per device.  Doing it this way means that we will probably need to build our own syncing mechanism (which we would have had to do anyways, cause chrome's sync storage makes me nervous).

**Comment by jessepollak** [comment]
There's no username stored in Cy? We do store site name though, which this
would remove.

I'm going to refactor again, write some tests, then merge.

**Comment by josephwegner** [comment]
Sorry, I meant sitename.  But I have the same issues with storing the sitename as I do with storing the username.  If someone broke into our database, they could get a list of all sites that a user has an account with.
