### ISSUE TITLE
Gmail Waltz Login failed

### ISSUE THREAD

**Issue by iamb55** [waltzio/waltz#80]
When I try to log in with Waltz, it tells me that I've got my password wrong.

**Comment by iamb55** [comment]
also, when I typed my password into google, I got logged into my generic google account. Not sure if this happens with waltz, but would be nice if the redirect was based on the URL where I started.

**Comment by jessepollak** [comment]
So, this seems to be something with them adding an additional check into the form through javascript when it is submitted...not shocked about this.

Don't know what to do. Any ideas?

**Comment by landakram** [comment]
After looking at this more, gmail generates a long hash using a script called `botguard`. It would take far too much energy to reverse engineer this script or figure out a way to run it.

It's much easier to just submit the actual login form instead of trying to generate the POST ourselves, so for select sites (like google), I'm just going to hide the waltz icon until the user is on the login page.
